FROM httpd:2.4
#RUN mkdir -p /usr/local/apache2/conf/sites/
#COPY ./http/ /usr/local/apache2/htdocs/
COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf
#COPY health-check.conf /usr/local/apache2/conf/sites/health-check.conf
EXPOSE 9090